export const GET_ISSUES_REQUEST = 'GET_ISSUES_REQUEST';
export const GET_ISSUES_SUCCESS = 'GET_ISSUES_SUCCESS';
export const GET_ISSUES_FAILED = 'GET_ISSUES_FAILED';

export const GET_ISSUE_BY_ID_REQUEST = 'GET_ISSUE_BY_ID_REQUEST';
export const GET_ISSUE_BY_ID_SUCCESS = 'GET_ISSUE_BY_ID_SUCCESS';
export const GET_ISSUE_BY_ID_FAILED = 'GET_ISSUE_BY_ID_FAILED';
